version: 2
updates:
  - package-ecosystem: npm
    directory: /api
    schedule:
      interval: weekly
    groups:
      api-dependencies:
        patterns: ["*"]

  - package-ecosystem: npm
    directory: /app
    schedule:
      interval: weekly
    groups:
      app-dependencies:
        patterns: ["*"]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
